"""add_lv_catalog_positions

Revision ID: 018702ce415c
Revises: 0ed682cb2e08
Create Date: 2026-03-21 15:45:52.687745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '018702ce415c'
down_revision: Union[str, None] = '0ed682cb2e08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lv_catalogs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('work_type', sa.String(length=50), nullable=True),
    sa.Column('is_template', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lv_catalogs_id'), 'lv_catalogs', ['id'], unique=False)
    op.create_table('lv_positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lv_id', sa.Integer(), nullable=False),
    sa.Column('position_nr', sa.String(length=20), nullable=True),
    sa.Column('short_description', sa.String(length=300), nullable=False),
    sa.Column('long_description', sa.Text(), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['lv_id'], ['lv_catalogs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lv_positions_id'), 'lv_positions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lv_positions_id'), table_name='lv_positions')
    op.drop_table('lv_positions')
    op.drop_index(op.f('ix_lv_catalogs_id'), table_name='lv_catalogs')
    op.drop_table('lv_catalogs')
    # ### end Alembic commands ###
