"""initial_schema

Revision ID: c01ff0394fd5
Revises: 
Create Date: 2026-03-21 14:30:23.381939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c01ff0394fd5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_report_site_date_user', 'daily_reports', ['site_id', 'report_date', 'created_by'])
    op.create_foreign_key(None, 'daily_reports', 'users', ['approved_by'], ['id'])
    op.create_foreign_key(None, 'users', 'sites', ['current_site_id'], ['id'])
    op.create_foreign_key(None, 'users', 'employees', ['employee_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'daily_reports', type_='foreignkey')
    op.drop_constraint('uq_report_site_date_user', 'daily_reports', type_='unique')
    # ### end Alembic commands ###
